#!/usr/bin/python3
# -*- coding: utf-8 -*-
import os
import re
import sys

repo_src = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src")
if os.path.isdir(repo_src) and repo_src not in sys.path:
    sys.path.insert(0, repo_src)

from lhpcdt.gfxconfig import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
