# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/codemodel_job_prop_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_codemodel_prop_form(object):
    def setupUi(self, codemodel_prop_form):
        codemodel_prop_form.setObjectName("codemodel_prop_form")
        codemodel_prop_form.setWindowModality(QtCore.Qt.ApplicationModal)
        codemodel_prop_form.resize(428, 260)
        codemodel_prop_form.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(codemodel_prop_form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.control_frame = QtWidgets.QFrame(codemodel_prop_form)
        self.control_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.control_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_frame.setObjectName("control_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.control_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.model_label = QtWidgets.QLabel(self.control_frame)
        self.model_label.setObjectName("model_label")
        self.gridLayout.addWidget(self.model_label, 0, 0, 1, 1)
        self.model_combo = QtWidgets.QComboBox(self.control_frame)
        self.model_combo.setEditable(True)
        self.model_combo.setObjectName("model_combo")
        self.gridLayout.addWidget(self.model_combo, 0, 1, 1, 1)
        self.models_dir_label = QtWidgets.QLabel(self.control_frame)
        self.models_dir_label.setObjectName("models_dir_label")
        self.gridLayout.addWidget(self.models_dir_label, 1, 0, 1, 1)
        self.models_dir_layout = QtWidgets.QHBoxLayout()
        self.models_dir_layout.setObjectName("models_dir_layout")
        self.models_dir_edit = QtWidgets.QLineEdit(self.control_frame)
        self.models_dir_edit.setObjectName("models_dir_edit")
        self.models_dir_layout.addWidget(self.models_dir_edit)
        self.browse_models_dir_button = QtWidgets.QPushButton(self.control_frame)
        self.browse_models_dir_button.setObjectName("browse_models_dir_button")
        self.models_dir_layout.addWidget(self.browse_models_dir_button)
        self.gridLayout.addLayout(self.models_dir_layout, 1, 1, 1, 1)
        self.models_dir_note_label = QtWidgets.QLabel(self.control_frame)
        self.models_dir_note_label.setWordWrap(True)
        self.models_dir_note_label.setObjectName("models_dir_note_label")
        self.gridLayout.addWidget(self.models_dir_note_label, 2, 0, 1, 2)
        self.extra_args_label = QtWidgets.QLabel(self.control_frame)
        self.extra_args_label.setObjectName("extra_args_label")
        self.gridLayout.addWidget(self.extra_args_label, 3, 0, 1, 1)
        self.extra_args_edit = QtWidgets.QLineEdit(self.control_frame)
        self.extra_args_edit.setObjectName("extra_args_edit")
        self.gridLayout.addWidget(self.extra_args_edit, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.control_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.ok_button = QtWidgets.QPushButton(codemodel_prop_form)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(codemodel_prop_form)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(codemodel_prop_form)
        QtCore.QMetaObject.connectSlotsByName(codemodel_prop_form)

    def retranslateUi(self, codemodel_prop_form):
        _translate = QtCore.QCoreApplication.translate
        codemodel_prop_form.setWindowTitle(_translate("codemodel_prop_form", "Code model job properties"))
        self.model_label.setText(_translate("codemodel_prop_form", "Code model"))
        self.model_combo.setToolTip(_translate("codemodel_prop_form", "Pick a popular code model, or type any other Ollama model tag"))
        self.models_dir_label.setText(_translate("codemodel_prop_form", "Model cache directory"))
        self.browse_models_dir_button.setText(_translate("codemodel_prop_form", "Browse..."))
        self.models_dir_note_label.setText(_translate("codemodel_prop_form", "Must be persistent storage - scratch or other temporary locations get purged, forcing the model to re-download on every launch."))
        self.extra_args_label.setText(_translate("codemodel_prop_form", "Extra ollama serve arguments"))
        self.ok_button.setText(_translate("codemodel_prop_form", "OK"))
        self.cancel_button.setText(_translate("codemodel_prop_form", "Cancel"))
