# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/codemodel_info_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_codemodel_info_form(object):
    def setupUi(self, codemodel_info_form):
        codemodel_info_form.setObjectName("codemodel_info_form")
        codemodel_info_form.resize(560, 420)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(codemodel_info_form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.heading_label = QtWidgets.QLabel(codemodel_info_form)
        self.heading_label.setWordWrap(True)
        self.heading_label.setObjectName("heading_label")
        self.verticalLayout_2.addWidget(self.heading_label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.endpoint_caption_label = QtWidgets.QLabel(codemodel_info_form)
        self.endpoint_caption_label.setObjectName("endpoint_caption_label")
        self.gridLayout.addWidget(self.endpoint_caption_label, 0, 0, 1, 1)
        self.endpoint_edit = QtWidgets.QLineEdit(codemodel_info_form)
        self.endpoint_edit.setReadOnly(True)
        self.endpoint_edit.setObjectName("endpoint_edit")
        self.gridLayout.addWidget(self.endpoint_edit, 0, 1, 1, 1)
        self.model_caption_label = QtWidgets.QLabel(codemodel_info_form)
        self.model_caption_label.setObjectName("model_caption_label")
        self.gridLayout.addWidget(self.model_caption_label, 1, 0, 1, 1)
        self.model_edit = QtWidgets.QLineEdit(codemodel_info_form)
        self.model_edit.setReadOnly(True)
        self.model_edit.setObjectName("model_edit")
        self.gridLayout.addWidget(self.model_edit, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.instructions_label = QtWidgets.QLabel(codemodel_info_form)
        self.instructions_label.setWordWrap(True)
        self.instructions_label.setObjectName("instructions_label")
        self.verticalLayout_2.addWidget(self.instructions_label)
        self.snippet_edit = QtWidgets.QPlainTextEdit(codemodel_info_form)
        self.snippet_edit.setReadOnly(True)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.snippet_edit.setFont(font)
        self.snippet_edit.setObjectName("snippet_edit")
        self.verticalLayout_2.addWidget(self.snippet_edit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.copy_button = QtWidgets.QPushButton(codemodel_info_form)
        self.copy_button.setObjectName("copy_button")
        self.horizontalLayout.addWidget(self.copy_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.close_button = QtWidgets.QPushButton(codemodel_info_form)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(codemodel_info_form)
        QtCore.QMetaObject.connectSlotsByName(codemodel_info_form)

    def retranslateUi(self, codemodel_info_form):
        _translate = QtCore.QCoreApplication.translate
        codemodel_info_form.setWindowTitle(_translate("codemodel_info_form", "VS Code connection info"))
        self.heading_label.setText(_translate("codemodel_info_form", "Your code model is running. Connect VS Code\'s Continue extension to it below."))
        self.endpoint_caption_label.setText(_translate("codemodel_info_form", "Endpoint"))
        self.model_caption_label.setText(_translate("codemodel_info_form", "Model"))
        self.instructions_label.setText(_translate("codemodel_info_form", "1. Install the Continue extension in VS Code.\n"
"2. Open Continue\'s config.json (gear icon in the Continue panel > Open config.json).\n"
"3. Paste the snippet below into the \"models\" array.\n"
"4. Keep this launcher window and the job running - the endpoint below is only reachable through the tunnel it set up, not from the open network."))
        self.copy_button.setText(_translate("codemodel_info_form", "Copy to clipboard"))
        self.close_button.setText(_translate("codemodel_info_form", "Close"))
